--[[
DO NOT EDIT
This file is autogenerated from gen_lib.lua
To regenerate this file, run `nvim -l gen_lib.lua`
--]]

local ffi=require"ffi"
ffi.cdef[=[
enum {ShapeInput=2};
enum {ShapeBounding=0};
typedef unsigned long XID;;
typedef XID XserverRegion;;
struct _XDisplay;
typedef struct _XDisplay Display;;
typedef struct { short x, y; unsigned short width, height; } XRectangle;;
XserverRegion XFixesCreateRegion (Display *dpy, XRectangle *rectangles, int nrectangles);;
void XFixesDestroyRegion (Display *dpy, XserverRegion region);;
typedef XID Window;;
void XFixesSetWindowShapeRegion (Display *dpy, Window win, int shape_kind, int x_off, int y_off, XserverRegion region);;
void XFixesInvertRegion (Display *dpy, XserverRegion dst, XRectangle *rect, XserverRegion src);;
]=]
return ffi.load"Xfixes" --[[@as table]]
