--[[
DO NOT EDIT
This file is autogenerated from wayland-scanner.lua
To regenerate this file, run `nvim -l gen/wayland-scanner.lua`
--]]

local ffi=require"ffi"
local wayland=require"nrwm.c.wayland"
local M={}
ffi.cdef[=[
struct river_window_manager_v1_listener {
void (*unavailable)(
void *data,
struct river_window_manager_v1 *river_window_manager_v1
);
void (*finished)(
void *data,
struct river_window_manager_v1 *river_window_manager_v1
);
void (*manage_start)(
void *data,
struct river_window_manager_v1 *river_window_manager_v1
);
void (*render_start)(
void *data,
struct river_window_manager_v1 *river_window_manager_v1
);
void (*session_locked)(
void *data,
struct river_window_manager_v1 *river_window_manager_v1
);
void (*session_unlocked)(
void *data,
struct river_window_manager_v1 *river_window_manager_v1
);
void (*window)(
void *data,
struct river_window_manager_v1 *river_window_manager_v1
,struct river_window_v1* id
);
void (*output)(
void *data,
struct river_window_manager_v1 *river_window_manager_v1
,struct river_output_v1* id
);
void (*seat)(
void *data,
struct river_window_manager_v1 *river_window_manager_v1
,struct river_seat_v1* id
);
};
]=]
M.river_window_manager_v1={
add_listener=function(river_window_manager_v1,listener,data)
return wayland.wl_proxy_add_listener(
ffi.cast("struct wl_proxy *", river_window_manager_v1),
ffi.cast("void (**)(void)", listener), data)
end,
error={
sequence_order = 0,
role = 1,
unresponsive = 2,
},
set_user_data=function(river_window_manager_v1,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", river_window_manager_v1), user_data)
end,
get_user_data=function(river_window_manager_v1)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", river_window_manager_v1))
end,
get_version=function(river_window_manager_v1)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", river_window_manager_v1))
end,
stop=function(river_window_manager_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_manager_v1)
,0
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_manager_v1))
, 0
)
end,
destroy=function(river_window_manager_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_manager_v1)
,1
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_manager_v1))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
manage_finish=function(river_window_manager_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_manager_v1)
,2
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_manager_v1))
, 0
)
end,
manage_dirty=function(river_window_manager_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_manager_v1)
,3
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_manager_v1))
, 0
)
end,
render_finish=function(river_window_manager_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_manager_v1)
,4
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_manager_v1))
, 0
)
end,
get_shell_surface=function(river_window_manager_v1
,surface
)
return ffi.cast("struct river_shell_surface_v1 *",
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_manager_v1)
,5
,M.river_shell_surface_v1.interface_ptr
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_manager_v1))
, 0
, ffi.cast("void*",nil)
, ffi.cast("struct wl_surface *",surface)
)
)
end,
exit_session=function(river_window_manager_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_manager_v1)
,6
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_manager_v1))
, 0
)
end,
interface_ptr=ffi.new("struct wl_interface[1]")
}
M.river_window_manager_v1.interface=M.river_window_manager_v1.interface_ptr[0]
ffi.cdef[=[
struct river_window_v1_listener {
void (*closed)(
void *data,
struct river_window_v1 *river_window_v1
);
void (*dimensions_hint)(
void *data,
struct river_window_v1 *river_window_v1
,int32_t min_width
,int32_t min_height
,int32_t max_width
,int32_t max_height
);
void (*dimensions)(
void *data,
struct river_window_v1 *river_window_v1
,int32_t width
,int32_t height
);
void (*app_id)(
void *data,
struct river_window_v1 *river_window_v1
,const char* app_id
);
void (*title)(
void *data,
struct river_window_v1 *river_window_v1
,const char* title
);
void (*parent)(
void *data,
struct river_window_v1 *river_window_v1
,struct river_window_v1* parent
);
void (*decoration_hint)(
void *data,
struct river_window_v1 *river_window_v1
,uint32_t hint
);
void (*pointer_move_requested)(
void *data,
struct river_window_v1 *river_window_v1
,struct river_seat_v1* seat
);
void (*pointer_resize_requested)(
void *data,
struct river_window_v1 *river_window_v1
,struct river_seat_v1* seat
,uint32_t edges
);
void (*show_window_menu_requested)(
void *data,
struct river_window_v1 *river_window_v1
,int32_t x
,int32_t y
);
void (*maximize_requested)(
void *data,
struct river_window_v1 *river_window_v1
);
void (*unmaximize_requested)(
void *data,
struct river_window_v1 *river_window_v1
);
void (*fullscreen_requested)(
void *data,
struct river_window_v1 *river_window_v1
,struct river_output_v1* output
);
void (*exit_fullscreen_requested)(
void *data,
struct river_window_v1 *river_window_v1
);
void (*minimize_requested)(
void *data,
struct river_window_v1 *river_window_v1
);
void (*unreliable_pid)(
void *data,
struct river_window_v1 *river_window_v1
,int32_t unreliable_pid
);
void (*presentation_hint)(
void *data,
struct river_window_v1 *river_window_v1
,uint32_t hint
);
void (*identifier)(
void *data,
struct river_window_v1 *river_window_v1
,const char* identifier
);
};
]=]
M.river_window_v1={
add_listener=function(river_window_v1,listener,data)
return wayland.wl_proxy_add_listener(
ffi.cast("struct wl_proxy *", river_window_v1),
ffi.cast("void (**)(void)", listener), data)
end,
error={
node_exists = 0,
invalid_dimensions = 1,
invalid_border = 2,
invalid_clip_box = 3,
},
decoration_hint={
only_supports_csd = 0,
prefers_csd = 1,
prefers_ssd = 2,
no_preference = 3,
},
edges={
none = 0,
top = 1,
bottom = 2,
left = 4,
right = 8,
},
capabilities={
window_menu = 1,
maximize = 2,
fullscreen = 4,
minimize = 8,
},
set_user_data=function(river_window_v1,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", river_window_v1), user_data)
end,
get_user_data=function(river_window_v1)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", river_window_v1))
end,
get_version=function(river_window_v1)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", river_window_v1))
end,
destroy=function(river_window_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,0
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
close=function(river_window_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,1
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
)
end,
get_node=function(river_window_v1
)
return ffi.cast("struct river_node_v1 *",
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,2
,M.river_node_v1.interface_ptr
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
, ffi.cast("void*",nil)
)
)
end,
propose_dimensions=function(river_window_v1
,width
,height
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,3
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
, ffi.cast("int32_t",width)
, ffi.cast("int32_t",height)
)
end,
hide=function(river_window_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,4
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
)
end,
show=function(river_window_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,5
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
)
end,
use_csd=function(river_window_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,6
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
)
end,
use_ssd=function(river_window_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,7
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
)
end,
set_borders=function(river_window_v1
,edges
,width
,r
,g
,b
,a
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,8
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
, ffi.cast("uint32_t",edges)
, ffi.cast("int32_t",width)
, ffi.cast("uint32_t",r)
, ffi.cast("uint32_t",g)
, ffi.cast("uint32_t",b)
, ffi.cast("uint32_t",a)
)
end,
set_tiled=function(river_window_v1
,edges
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,9
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
, ffi.cast("uint32_t",edges)
)
end,
get_decoration_above=function(river_window_v1
,surface
)
return ffi.cast("struct river_decoration_v1 *",
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,10
,M.river_decoration_v1.interface_ptr
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
, ffi.cast("void*",nil)
, ffi.cast("struct wl_surface *",surface)
)
)
end,
get_decoration_below=function(river_window_v1
,surface
)
return ffi.cast("struct river_decoration_v1 *",
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,11
,M.river_decoration_v1.interface_ptr
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
, ffi.cast("void*",nil)
, ffi.cast("struct wl_surface *",surface)
)
)
end,
inform_resize_start=function(river_window_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,12
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
)
end,
inform_resize_end=function(river_window_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,13
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
)
end,
set_capabilities=function(river_window_v1
,caps
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,14
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
, ffi.cast("uint32_t",caps)
)
end,
inform_maximized=function(river_window_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,15
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
)
end,
inform_unmaximized=function(river_window_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,16
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
)
end,
inform_fullscreen=function(river_window_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,17
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
)
end,
inform_not_fullscreen=function(river_window_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,18
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
)
end,
fullscreen=function(river_window_v1
,output
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,19
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
, ffi.cast("struct river_output_v1 *",output)
)
end,
exit_fullscreen=function(river_window_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,20
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
)
end,
set_clip_box=function(river_window_v1
,x
,y
,width
,height
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,21
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
, ffi.cast("int32_t",x)
, ffi.cast("int32_t",y)
, ffi.cast("int32_t",width)
, ffi.cast("int32_t",height)
)
end,
set_content_clip_box=function(river_window_v1
,x
,y
,width
,height
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,22
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
, ffi.cast("int32_t",x)
, ffi.cast("int32_t",y)
, ffi.cast("int32_t",width)
, ffi.cast("int32_t",height)
)
end,
set_dimension_bounds=function(river_window_v1
,max_width
,max_height
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_window_v1)
,23
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_window_v1))
, 0
, ffi.cast("int32_t",max_width)
, ffi.cast("int32_t",max_height)
)
end,
interface_ptr=ffi.new("struct wl_interface[1]")
}
M.river_window_v1.interface=M.river_window_v1.interface_ptr[0]
M.river_decoration_v1={
error={
no_commit = 0,
},
set_user_data=function(river_decoration_v1,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", river_decoration_v1), user_data)
end,
get_user_data=function(river_decoration_v1)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", river_decoration_v1))
end,
get_version=function(river_decoration_v1)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", river_decoration_v1))
end,
destroy=function(river_decoration_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_decoration_v1)
,0
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_decoration_v1))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
set_offset=function(river_decoration_v1
,x
,y
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_decoration_v1)
,1
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_decoration_v1))
, 0
, ffi.cast("int32_t",x)
, ffi.cast("int32_t",y)
)
end,
sync_next_commit=function(river_decoration_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_decoration_v1)
,2
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_decoration_v1))
, 0
)
end,
interface_ptr=ffi.new("struct wl_interface[1]")
}
M.river_decoration_v1.interface=M.river_decoration_v1.interface_ptr[0]
M.river_shell_surface_v1={
error={
node_exists = 0,
no_commit = 1,
},
set_user_data=function(river_shell_surface_v1,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", river_shell_surface_v1), user_data)
end,
get_user_data=function(river_shell_surface_v1)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", river_shell_surface_v1))
end,
get_version=function(river_shell_surface_v1)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", river_shell_surface_v1))
end,
destroy=function(river_shell_surface_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_shell_surface_v1)
,0
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_shell_surface_v1))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
get_node=function(river_shell_surface_v1
)
return ffi.cast("struct river_node_v1 *",
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_shell_surface_v1)
,1
,M.river_node_v1.interface_ptr
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_shell_surface_v1))
, 0
, ffi.cast("void*",nil)
)
)
end,
sync_next_commit=function(river_shell_surface_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_shell_surface_v1)
,2
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_shell_surface_v1))
, 0
)
end,
interface_ptr=ffi.new("struct wl_interface[1]")
}
M.river_shell_surface_v1.interface=M.river_shell_surface_v1.interface_ptr[0]
M.river_node_v1={
set_user_data=function(river_node_v1,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", river_node_v1), user_data)
end,
get_user_data=function(river_node_v1)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", river_node_v1))
end,
get_version=function(river_node_v1)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", river_node_v1))
end,
destroy=function(river_node_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_node_v1)
,0
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_node_v1))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
set_position=function(river_node_v1
,x
,y
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_node_v1)
,1
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_node_v1))
, 0
, ffi.cast("int32_t",x)
, ffi.cast("int32_t",y)
)
end,
place_top=function(river_node_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_node_v1)
,2
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_node_v1))
, 0
)
end,
place_bottom=function(river_node_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_node_v1)
,3
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_node_v1))
, 0
)
end,
place_above=function(river_node_v1
,other
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_node_v1)
,4
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_node_v1))
, 0
, ffi.cast("struct river_node_v1 *",other)
)
end,
place_below=function(river_node_v1
,other
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_node_v1)
,5
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_node_v1))
, 0
, ffi.cast("struct river_node_v1 *",other)
)
end,
interface_ptr=ffi.new("struct wl_interface[1]")
}
M.river_node_v1.interface=M.river_node_v1.interface_ptr[0]
ffi.cdef[=[
struct river_output_v1_listener {
void (*removed)(
void *data,
struct river_output_v1 *river_output_v1
);
void (*wl_output)(
void *data,
struct river_output_v1 *river_output_v1
,uint32_t name
);
void (*position)(
void *data,
struct river_output_v1 *river_output_v1
,int32_t x
,int32_t y
);
void (*dimensions)(
void *data,
struct river_output_v1 *river_output_v1
,int32_t width
,int32_t height
);
};
]=]
M.river_output_v1={
add_listener=function(river_output_v1,listener,data)
return wayland.wl_proxy_add_listener(
ffi.cast("struct wl_proxy *", river_output_v1),
ffi.cast("void (**)(void)", listener), data)
end,
error={
invalid_presentation_mode = 0,
},
presentation_mode={
vsync = 0,
async = 1,
},
set_user_data=function(river_output_v1,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", river_output_v1), user_data)
end,
get_user_data=function(river_output_v1)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", river_output_v1))
end,
get_version=function(river_output_v1)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", river_output_v1))
end,
destroy=function(river_output_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_output_v1)
,0
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_output_v1))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
set_presentation_mode=function(river_output_v1
,mode
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_output_v1)
,1
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_output_v1))
, 0
, ffi.cast("uint32_t",mode)
)
end,
interface_ptr=ffi.new("struct wl_interface[1]")
}
M.river_output_v1.interface=M.river_output_v1.interface_ptr[0]
ffi.cdef[=[
struct river_seat_v1_listener {
void (*removed)(
void *data,
struct river_seat_v1 *river_seat_v1
);
void (*wl_seat)(
void *data,
struct river_seat_v1 *river_seat_v1
,uint32_t name
);
void (*pointer_enter)(
void *data,
struct river_seat_v1 *river_seat_v1
,struct river_window_v1* window
);
void (*pointer_leave)(
void *data,
struct river_seat_v1 *river_seat_v1
);
void (*window_interaction)(
void *data,
struct river_seat_v1 *river_seat_v1
,struct river_window_v1* window
);
void (*shell_surface_interaction)(
void *data,
struct river_seat_v1 *river_seat_v1
,struct river_shell_surface_v1* shell_surface
);
void (*op_delta)(
void *data,
struct river_seat_v1 *river_seat_v1
,int32_t dx
,int32_t dy
);
void (*op_release)(
void *data,
struct river_seat_v1 *river_seat_v1
);
void (*pointer_position)(
void *data,
struct river_seat_v1 *river_seat_v1
,int32_t x
,int32_t y
);
};
]=]
M.river_seat_v1={
add_listener=function(river_seat_v1,listener,data)
return wayland.wl_proxy_add_listener(
ffi.cast("struct wl_proxy *", river_seat_v1),
ffi.cast("void (**)(void)", listener), data)
end,
modifiers={
none = 0,
shift = 1,
ctrl = 4,
mod1 = 8,
mod3 = 32,
mod4 = 64,
mod5 = 128,
},
set_user_data=function(river_seat_v1,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", river_seat_v1), user_data)
end,
get_user_data=function(river_seat_v1)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", river_seat_v1))
end,
get_version=function(river_seat_v1)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", river_seat_v1))
end,
destroy=function(river_seat_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_seat_v1)
,0
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_seat_v1))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
focus_window=function(river_seat_v1
,window
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_seat_v1)
,1
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_seat_v1))
, 0
, ffi.cast("struct river_window_v1 *",window)
)
end,
focus_shell_surface=function(river_seat_v1
,shell_surface
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_seat_v1)
,2
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_seat_v1))
, 0
, ffi.cast("struct river_shell_surface_v1 *",shell_surface)
)
end,
clear_focus=function(river_seat_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_seat_v1)
,3
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_seat_v1))
, 0
)
end,
op_start_pointer=function(river_seat_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_seat_v1)
,4
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_seat_v1))
, 0
)
end,
op_end=function(river_seat_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_seat_v1)
,5
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_seat_v1))
, 0
)
end,
get_pointer_binding=function(river_seat_v1
,button
,modifiers
)
return ffi.cast("struct river_pointer_binding_v1 *",
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_seat_v1)
,6
,M.river_pointer_binding_v1.interface_ptr
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_seat_v1))
, 0
, ffi.cast("void*",nil)
, ffi.cast("uint32_t",button)
, ffi.cast("uint32_t",modifiers)
)
)
end,
set_xcursor_theme=function(river_seat_v1
,name
,size
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_seat_v1)
,7
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_seat_v1))
, 0
, ffi.cast("const char*",name)
, ffi.cast("uint32_t",size)
)
end,
pointer_warp=function(river_seat_v1
,x
,y
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_seat_v1)
,8
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_seat_v1))
, 0
, ffi.cast("int32_t",x)
, ffi.cast("int32_t",y)
)
end,
interface_ptr=ffi.new("struct wl_interface[1]")
}
M.river_seat_v1.interface=M.river_seat_v1.interface_ptr[0]
ffi.cdef[=[
struct river_pointer_binding_v1_listener {
void (*pressed)(
void *data,
struct river_pointer_binding_v1 *river_pointer_binding_v1
);
void (*released)(
void *data,
struct river_pointer_binding_v1 *river_pointer_binding_v1
);
};
]=]
M.river_pointer_binding_v1={
add_listener=function(river_pointer_binding_v1,listener,data)
return wayland.wl_proxy_add_listener(
ffi.cast("struct wl_proxy *", river_pointer_binding_v1),
ffi.cast("void (**)(void)", listener), data)
end,
set_user_data=function(river_pointer_binding_v1,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", river_pointer_binding_v1), user_data)
end,
get_user_data=function(river_pointer_binding_v1)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", river_pointer_binding_v1))
end,
get_version=function(river_pointer_binding_v1)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", river_pointer_binding_v1))
end,
destroy=function(river_pointer_binding_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_pointer_binding_v1)
,0
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_pointer_binding_v1))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
enable=function(river_pointer_binding_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_pointer_binding_v1)
,1
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_pointer_binding_v1))
, 0
)
end,
disable=function(river_pointer_binding_v1
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", river_pointer_binding_v1)
,2
,nil
, wayland.wl_proxy_get_version(ffi.cast("struct wl_proxy *", river_pointer_binding_v1))
, 0
)
end,
interface_ptr=ffi.new("struct wl_interface[1]")
}
M.river_pointer_binding_v1.interface=M.river_pointer_binding_v1.interface_ptr[0]
local function ptr_reference_hack(val)
local hex=assert(tostring(val):match("0x(%x*)$"))
local n=ffi.new("intptr_t",tonumber(hex:sub(1,-9),16))
n=bit.lshift(n,32)+tonumber(hex:sub(-8),16)
return ffi.cast("struct wl_interface*",n)
end
ffi.cdef[[
extern const struct wl_interface wl_surface_interface;
]]
local external={
wl_surface=ptr_reference_hack(wayland.wl_surface_interface),
}
local args_types_river_node_v1_place_above=ffi.new("const struct wl_interface*[1]",{
M.river_node_v1.interface_ptr,
})
local args_types_river_node_v1_place_below=ffi.new("const struct wl_interface*[1]",{
M.river_node_v1.interface_ptr,
})
local args_types_river_seat_v1_focus_shell_surface=ffi.new("const struct wl_interface*[1]",{
M.river_shell_surface_v1.interface_ptr,
})
local args_types_river_seat_v1_focus_window=ffi.new("const struct wl_interface*[1]",{
M.river_window_v1.interface_ptr,
})
local args_types_river_seat_v1_get_pointer_binding=ffi.new("const struct wl_interface*[3]",{
M.river_pointer_binding_v1.interface_ptr,
nil,
nil,
})
local args_types_river_seat_v1_pointer_enter=ffi.new("const struct wl_interface*[1]",{
M.river_window_v1.interface_ptr,
})
local args_types_river_seat_v1_shell_surface_interaction=ffi.new("const struct wl_interface*[1]",{
M.river_shell_surface_v1.interface_ptr,
})
local args_types_river_seat_v1_window_interaction=ffi.new("const struct wl_interface*[1]",{
M.river_window_v1.interface_ptr,
})
local args_types_river_shell_surface_v1_get_node=ffi.new("const struct wl_interface*[1]",{
M.river_node_v1.interface_ptr,
})
local args_types_river_window_manager_v1_get_shell_surface=ffi.new("const struct wl_interface*[2]",{
M.river_shell_surface_v1.interface_ptr,
external.wl_surface,
})
local args_types_river_window_manager_v1_output=ffi.new("const struct wl_interface*[1]",{
M.river_output_v1.interface_ptr,
})
local args_types_river_window_manager_v1_seat=ffi.new("const struct wl_interface*[1]",{
M.river_seat_v1.interface_ptr,
})
local args_types_river_window_manager_v1_window=ffi.new("const struct wl_interface*[1]",{
M.river_window_v1.interface_ptr,
})
local args_types_river_window_v1_fullscreen=ffi.new("const struct wl_interface*[1]",{
M.river_output_v1.interface_ptr,
})
local args_types_river_window_v1_fullscreen_requested=ffi.new("const struct wl_interface*[1]",{
M.river_output_v1.interface_ptr,
})
local args_types_river_window_v1_get_decoration_above=ffi.new("const struct wl_interface*[2]",{
M.river_decoration_v1.interface_ptr,
external.wl_surface,
})
local args_types_river_window_v1_get_decoration_below=ffi.new("const struct wl_interface*[2]",{
M.river_decoration_v1.interface_ptr,
external.wl_surface,
})
local args_types_river_window_v1_get_node=ffi.new("const struct wl_interface*[1]",{
M.river_node_v1.interface_ptr,
})
local args_types_river_window_v1_parent=ffi.new("const struct wl_interface*[1]",{
M.river_window_v1.interface_ptr,
})
local args_types_river_window_v1_pointer_move_requested=ffi.new("const struct wl_interface*[1]",{
M.river_seat_v1.interface_ptr,
})
local args_types_river_window_v1_pointer_resize_requested=ffi.new("const struct wl_interface*[2]",{
M.river_seat_v1.interface_ptr,
nil,
})
local args_types_nil=ffi.new("const struct wl_interface*[6]",{
nil,
nil,
nil,
nil,
nil,
nil,
})
local river_window_manager_v1_requests=ffi.new("struct wl_message[7]",{
{"stop",
"",
args_types_nil
},
{"destroy",
"",
args_types_nil
},
{"manage_finish",
"",
args_types_nil
},
{"manage_dirty",
"",
args_types_nil
},
{"render_finish",
"",
args_types_nil
},
{"get_shell_surface",
"no",
args_types_river_window_manager_v1_get_shell_surface
},
{"exit_session",
"4",
args_types_nil
},
})
local river_window_manager_v1_events=ffi.new("struct wl_message[9]",{
{"unavailable",
"",
args_types_nil
},
{"finished",
"",
args_types_nil
},
{"manage_start",
"",
args_types_nil
},
{"render_start",
"",
args_types_nil
},
{"session_locked",
"",
args_types_nil
},
{"session_unlocked",
"",
args_types_nil
},
{"window",
"n",
args_types_river_window_manager_v1_window
},
{"output",
"n",
args_types_river_window_manager_v1_output
},
{"seat",
"n",
args_types_river_window_manager_v1_seat
},
})
M.river_window_manager_v1.interface.name="river_window_manager_v1"
M.river_window_manager_v1.interface.version=4
M.river_window_manager_v1.interface.method_count=7
M.river_window_manager_v1.interface.methods=river_window_manager_v1_requests
M.river_window_manager_v1.interface.event_count=9
M.river_window_manager_v1.interface.events=river_window_manager_v1_events
local river_window_v1_requests=ffi.new("struct wl_message[24]",{
{"destroy",
"",
args_types_nil
},
{"close",
"",
args_types_nil
},
{"get_node",
"n",
args_types_river_window_v1_get_node
},
{"propose_dimensions",
"ii",
args_types_nil
},
{"hide",
"",
args_types_nil
},
{"show",
"",
args_types_nil
},
{"use_csd",
"",
args_types_nil
},
{"use_ssd",
"",
args_types_nil
},
{"set_borders",
"uiuuuu",
args_types_nil
},
{"set_tiled",
"u",
args_types_nil
},
{"get_decoration_above",
"no",
args_types_river_window_v1_get_decoration_above
},
{"get_decoration_below",
"no",
args_types_river_window_v1_get_decoration_below
},
{"inform_resize_start",
"",
args_types_nil
},
{"inform_resize_end",
"",
args_types_nil
},
{"set_capabilities",
"u",
args_types_nil
},
{"inform_maximized",
"",
args_types_nil
},
{"inform_unmaximized",
"",
args_types_nil
},
{"inform_fullscreen",
"",
args_types_nil
},
{"inform_not_fullscreen",
"",
args_types_nil
},
{"fullscreen",
"o",
args_types_river_window_v1_fullscreen
},
{"exit_fullscreen",
"",
args_types_nil
},
{"set_clip_box",
"2iiii",
args_types_nil
},
{"set_content_clip_box",
"3iiii",
args_types_nil
},
{"set_dimension_bounds",
"4ii",
args_types_nil
},
})
local river_window_v1_events=ffi.new("struct wl_message[18]",{
{"closed",
"",
args_types_nil
},
{"dimensions_hint",
"iiii",
args_types_nil
},
{"dimensions",
"ii",
args_types_nil
},
{"app_id",
"?s",
args_types_nil
},
{"title",
"?s",
args_types_nil
},
{"parent",
"?o",
args_types_river_window_v1_parent
},
{"decoration_hint",
"u",
args_types_nil
},
{"pointer_move_requested",
"o",
args_types_river_window_v1_pointer_move_requested
},
{"pointer_resize_requested",
"ou",
args_types_river_window_v1_pointer_resize_requested
},
{"show_window_menu_requested",
"ii",
args_types_nil
},
{"maximize_requested",
"",
args_types_nil
},
{"unmaximize_requested",
"",
args_types_nil
},
{"fullscreen_requested",
"?o",
args_types_river_window_v1_fullscreen_requested
},
{"exit_fullscreen_requested",
"",
args_types_nil
},
{"minimize_requested",
"",
args_types_nil
},
{"unreliable_pid",
"2i",
args_types_nil
},
{"presentation_hint",
"4u",
args_types_nil
},
{"identifier",
"4s",
args_types_nil
},
})
M.river_window_v1.interface.name="river_window_v1"
M.river_window_v1.interface.version=4
M.river_window_v1.interface.method_count=24
M.river_window_v1.interface.methods=river_window_v1_requests
M.river_window_v1.interface.event_count=18
M.river_window_v1.interface.events=river_window_v1_events
local river_decoration_v1_requests=ffi.new("struct wl_message[3]",{
{"destroy",
"",
args_types_nil
},
{"set_offset",
"ii",
args_types_nil
},
{"sync_next_commit",
"",
args_types_nil
},
})
M.river_decoration_v1.interface.name="river_decoration_v1"
M.river_decoration_v1.interface.version=4
M.river_decoration_v1.interface.method_count=3
M.river_decoration_v1.interface.methods=river_decoration_v1_requests
M.river_decoration_v1.interface.event_count=0
M.river_decoration_v1.interface.events=nil
local river_shell_surface_v1_requests=ffi.new("struct wl_message[3]",{
{"destroy",
"",
args_types_nil
},
{"get_node",
"n",
args_types_river_shell_surface_v1_get_node
},
{"sync_next_commit",
"",
args_types_nil
},
})
M.river_shell_surface_v1.interface.name="river_shell_surface_v1"
M.river_shell_surface_v1.interface.version=4
M.river_shell_surface_v1.interface.method_count=3
M.river_shell_surface_v1.interface.methods=river_shell_surface_v1_requests
M.river_shell_surface_v1.interface.event_count=0
M.river_shell_surface_v1.interface.events=nil
local river_node_v1_requests=ffi.new("struct wl_message[6]",{
{"destroy",
"",
args_types_nil
},
{"set_position",
"ii",
args_types_nil
},
{"place_top",
"",
args_types_nil
},
{"place_bottom",
"",
args_types_nil
},
{"place_above",
"o",
args_types_river_node_v1_place_above
},
{"place_below",
"o",
args_types_river_node_v1_place_below
},
})
M.river_node_v1.interface.name="river_node_v1"
M.river_node_v1.interface.version=4
M.river_node_v1.interface.method_count=6
M.river_node_v1.interface.methods=river_node_v1_requests
M.river_node_v1.interface.event_count=0
M.river_node_v1.interface.events=nil
local river_output_v1_requests=ffi.new("struct wl_message[2]",{
{"destroy",
"",
args_types_nil
},
{"set_presentation_mode",
"4u",
args_types_nil
},
})
local river_output_v1_events=ffi.new("struct wl_message[4]",{
{"removed",
"",
args_types_nil
},
{"wl_output",
"u",
args_types_nil
},
{"position",
"ii",
args_types_nil
},
{"dimensions",
"ii",
args_types_nil
},
})
M.river_output_v1.interface.name="river_output_v1"
M.river_output_v1.interface.version=4
M.river_output_v1.interface.method_count=2
M.river_output_v1.interface.methods=river_output_v1_requests
M.river_output_v1.interface.event_count=4
M.river_output_v1.interface.events=river_output_v1_events
local river_seat_v1_requests=ffi.new("struct wl_message[9]",{
{"destroy",
"",
args_types_nil
},
{"focus_window",
"o",
args_types_river_seat_v1_focus_window
},
{"focus_shell_surface",
"o",
args_types_river_seat_v1_focus_shell_surface
},
{"clear_focus",
"",
args_types_nil
},
{"op_start_pointer",
"",
args_types_nil
},
{"op_end",
"",
args_types_nil
},
{"get_pointer_binding",
"nuu",
args_types_river_seat_v1_get_pointer_binding
},
{"set_xcursor_theme",
"2su",
args_types_nil
},
{"pointer_warp",
"3ii",
args_types_nil
},
})
local river_seat_v1_events=ffi.new("struct wl_message[9]",{
{"removed",
"",
args_types_nil
},
{"wl_seat",
"u",
args_types_nil
},
{"pointer_enter",
"o",
args_types_river_seat_v1_pointer_enter
},
{"pointer_leave",
"",
args_types_nil
},
{"window_interaction",
"o",
args_types_river_seat_v1_window_interaction
},
{"shell_surface_interaction",
"o",
args_types_river_seat_v1_shell_surface_interaction
},
{"op_delta",
"ii",
args_types_nil
},
{"op_release",
"",
args_types_nil
},
{"pointer_position",
"2ii",
args_types_nil
},
})
M.river_seat_v1.interface.name="river_seat_v1"
M.river_seat_v1.interface.version=4
M.river_seat_v1.interface.method_count=9
M.river_seat_v1.interface.methods=river_seat_v1_requests
M.river_seat_v1.interface.event_count=9
M.river_seat_v1.interface.events=river_seat_v1_events
local river_pointer_binding_v1_requests=ffi.new("struct wl_message[3]",{
{"destroy",
"",
args_types_nil
},
{"enable",
"",
args_types_nil
},
{"disable",
"",
args_types_nil
},
})
local river_pointer_binding_v1_events=ffi.new("struct wl_message[2]",{
{"pressed",
"",
args_types_nil
},
{"released",
"",
args_types_nil
},
})
M.river_pointer_binding_v1.interface.name="river_pointer_binding_v1"
M.river_pointer_binding_v1.interface.version=4
M.river_pointer_binding_v1.interface.method_count=3
M.river_pointer_binding_v1.interface.methods=river_pointer_binding_v1_requests
M.river_pointer_binding_v1.interface.event_count=2
M.river_pointer_binding_v1.interface.events=river_pointer_binding_v1_events
return M
