--[[
DO NOT EDIT
This file is autogenerated from wayland-scanner.lua
To regenerate this file, run `nvim -l gen/wayland-scanner.lua`
--]]

local ffi=require"ffi"
local wayland=require"nrwm.c.wayland"
local M={}
ffi.cdef[=[
struct wl_display_listener {
void (*error)(
void *data,
struct wl_display *wl_display
,void* object_id
,uint32_t code
,const char* message
);
void (*delete_id)(
void *data,
struct wl_display *wl_display
,uint32_t id
);
};
]=]
M.wl_display={
add_listener=function(wl_display,listener,data)
return wayland.wl_proxy_add_listener(
ffi.cast("struct wl_proxy *", wl_display),
ffi.cast("void (**)(void)", listener), data)
end,
error={
invalid_object = 0,
invalid_method = 1,
no_memory = 2,
implementation = 3,
},
set_user_data=function(wl_display,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_display), user_data)
end,
get_user_data=function(wl_display)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_display))
end,
get_version=function(wl_display)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_display))
end,
sync=function(wl_display
)
return ffi.cast("struct wl_callback *",
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_display)
,0
,M.wl_callback.interface
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_display))
, 0
, callback
)
)
end,
get_registry=function(wl_display
)
return ffi.cast("struct wl_registry *",
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_display)
,1
,M.wl_registry.interface
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_display))
, 0
, registry
)
)
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_display.interface)
ffi.cdef[=[
struct wl_registry_listener {
void (*global)(
void *data,
struct wl_registry *wl_registry
,uint32_t name
,const char* interface
,uint32_t version
);
void (*global_remove)(
void *data,
struct wl_registry *wl_registry
,uint32_t name
);
};
]=]
M.wl_registry={
add_listener=function(wl_registry,listener,data)
return wayland.wl_proxy_add_listener(
ffi.cast("struct wl_proxy *", wl_registry),
ffi.cast("void (**)(void)", listener), data)
end,
set_user_data=function(wl_registry,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_registry), user_data)
end,
get_user_data=function(wl_registry)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_registry))
end,
get_version=function(wl_registry)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_registry))
end,
destroy=function(wl_registry)
return wayland.wl_proxy_destroy(
ffi.cast("struct wl_proxy *", wl_registry))
end,
bind=function(wl_registry
,name
,interface,version
)
return ffi.cast("void*",
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_registry)
,0
,interface
, version
, 0
, name
, id
)
)
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_registry.interface)
ffi.cdef[=[
struct wl_callback_listener {
void (*done)(
void *data,
struct wl_callback *wl_callback
,uint32_t callback_data
);
};
]=]
M.wl_callback={
add_listener=function(wl_callback,listener,data)
return wayland.wl_proxy_add_listener(
ffi.cast("struct wl_proxy *", wl_callback),
ffi.cast("void (**)(void)", listener), data)
end,
set_user_data=function(wl_callback,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_callback), user_data)
end,
get_user_data=function(wl_callback)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_callback))
end,
get_version=function(wl_callback)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_callback))
end,
destroy=function(wl_callback)
return wayland.wl_proxy_destroy(
ffi.cast("struct wl_proxy *", wl_callback))
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_callback.interface)
M.wl_compositor={
set_user_data=function(wl_compositor,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_compositor), user_data)
end,
get_user_data=function(wl_compositor)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_compositor))
end,
get_version=function(wl_compositor)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_compositor))
end,
create_surface=function(wl_compositor
)
return ffi.cast("struct wl_surface *",
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_compositor)
,0
,M.wl_surface.interface
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_compositor))
, 0
, id
)
)
end,
create_region=function(wl_compositor
)
return ffi.cast("struct wl_region *",
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_compositor)
,1
,M.wl_region.interface
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_compositor))
, 0
, id
)
)
end,
release=function(wl_compositor
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_compositor)
,2
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_compositor))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_compositor.interface)
M.wl_shm_pool={
set_user_data=function(wl_shm_pool,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_shm_pool), user_data)
end,
get_user_data=function(wl_shm_pool)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_shm_pool))
end,
get_version=function(wl_shm_pool)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_shm_pool))
end,
create_buffer=function(wl_shm_pool
,offset
,width
,height
,stride
,format
)
return ffi.cast("struct wl_buffer *",
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_shm_pool)
,0
,M.wl_buffer.interface
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_shm_pool))
, 0
, id
, offset
, width
, height
, stride
, format
)
)
end,
destroy=function(wl_shm_pool
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_shm_pool)
,1
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_shm_pool))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
resize=function(wl_shm_pool
,size
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_shm_pool)
,2
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_shm_pool))
, 0
, size
)
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_shm_pool.interface)
ffi.cdef[=[
struct wl_shm_listener {
void (*format)(
void *data,
struct wl_shm *wl_shm
,uint32_t format
);
};
]=]
M.wl_shm={
add_listener=function(wl_shm,listener,data)
return wayland.wl_proxy_add_listener(
ffi.cast("struct wl_proxy *", wl_shm),
ffi.cast("void (**)(void)", listener), data)
end,
error={
invalid_format = 0,
invalid_stride = 1,
invalid_fd = 2,
},
format={
argb8888 = 0,
xrgb8888 = 1,
c8 = 538982467,
rgb332 = 943867730,
bgr233 = 944916290,
xrgb4444 = 842093144,
xbgr4444 = 842089048,
rgbx4444 = 842094674,
bgrx4444 = 842094658,
argb4444 = 842093121,
abgr4444 = 842089025,
rgba4444 = 842088786,
bgra4444 = 842088770,
xrgb1555 = 892424792,
xbgr1555 = 892420696,
rgbx5551 = 892426322,
bgrx5551 = 892426306,
argb1555 = 892424769,
abgr1555 = 892420673,
rgba5551 = 892420434,
bgra5551 = 892420418,
rgb565 = 909199186,
bgr565 = 909199170,
rgb888 = 875710290,
bgr888 = 875710274,
xbgr8888 = 875709016,
rgbx8888 = 875714642,
bgrx8888 = 875714626,
abgr8888 = 875708993,
rgba8888 = 875708754,
bgra8888 = 875708738,
xrgb2101010 = 808669784,
xbgr2101010 = 808665688,
rgbx1010102 = 808671314,
bgrx1010102 = 808671298,
argb2101010 = 808669761,
abgr2101010 = 808665665,
rgba1010102 = 808665426,
bgra1010102 = 808665410,
yuyv = 1448695129,
yvyu = 1431918169,
uyvy = 1498831189,
vyuy = 1498765654,
ayuv = 1448433985,
nv12 = 842094158,
nv21 = 825382478,
nv16 = 909203022,
nv61 = 825644622,
yuv410 = 961959257,
yvu410 = 961893977,
yuv411 = 825316697,
yvu411 = 825316953,
yuv420 = 842093913,
yvu420 = 842094169,
yuv422 = 909202777,
yvu422 = 909203033,
yuv444 = 875713881,
yvu444 = 875714137,
r8 = 538982482,
r16 = 540422482,
rg88 = 943212370,
gr88 = 943215175,
rg1616 = 842221394,
gr1616 = 842224199,
xrgb16161616f = 1211388504,
xbgr16161616f = 1211384408,
argb16161616f = 1211388481,
abgr16161616f = 1211384385,
xyuv8888 = 1448434008,
vuy888 = 875713878,
vuy101010 = 808670550,
y210 = 808530521,
y212 = 842084953,
y216 = 909193817,
y410 = 808531033,
y412 = 842085465,
y416 = 909194329,
xvyu2101010 = 808670808,
xvyu12_16161616 = 909334104,
xvyu16161616 = 942954072,
y0l0 = 810299481,
x0l0 = 810299480,
y0l2 = 843853913,
x0l2 = 843853912,
yuv420_8bit = 942691673,
yuv420_10bit = 808539481,
xrgb8888_a8 = 943805016,
xbgr8888_a8 = 943800920,
rgbx8888_a8 = 943806546,
bgrx8888_a8 = 943806530,
rgb888_a8 = 943798354,
bgr888_a8 = 943798338,
rgb565_a8 = 943797586,
bgr565_a8 = 943797570,
nv24 = 875714126,
nv42 = 842290766,
p210 = 808530512,
p010 = 808530000,
p012 = 842084432,
p016 = 909193296,
axbxgxrx106106106106 = 808534593,
nv15 = 892425806,
q410 = 808531025,
q401 = 825242705,
xrgb16161616 = 942953048,
xbgr16161616 = 942948952,
argb16161616 = 942953025,
abgr16161616 = 942948929,
c1 = 538980675,
c2 = 538980931,
c4 = 538981443,
d1 = 538980676,
d2 = 538980932,
d4 = 538981444,
d8 = 538982468,
r1 = 538980690,
r2 = 538980946,
r4 = 538981458,
r10 = 540029266,
r12 = 540160338,
avuy8888 = 1498764865,
xvuy8888 = 1498764888,
p030 = 808661072,
rgb161616 = 942950226,
bgr161616 = 942950210,
r16f = 1210064978,
gr1616f = 1210077767,
bgr161616f = 1213351746,
r32f = 1176510546,
gr3232f = 1176523335,
bgr323232f = 1179797314,
abgr32323232f = 1178092097,
nv20 = 808605262,
nv30 = 808670798,
s010 = 808530003,
s210 = 808530515,
s410 = 808531027,
s012 = 842084435,
s212 = 842084947,
s412 = 842085459,
s016 = 909193299,
s216 = 909193811,
s416 = 909194323,
},
set_user_data=function(wl_shm,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_shm), user_data)
end,
get_user_data=function(wl_shm)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_shm))
end,
get_version=function(wl_shm)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_shm))
end,
create_pool=function(wl_shm
,fd
,size
)
return ffi.cast("struct wl_shm_pool *",
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_shm)
,0
,M.wl_shm_pool.interface
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_shm))
, 0
, id
, fd
, size
)
)
end,
release=function(wl_shm
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_shm)
,1
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_shm))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_shm.interface)
ffi.cdef[=[
struct wl_buffer_listener {
void (*release)(
void *data,
struct wl_buffer *wl_buffer
);
};
]=]
M.wl_buffer={
add_listener=function(wl_buffer,listener,data)
return wayland.wl_proxy_add_listener(
ffi.cast("struct wl_proxy *", wl_buffer),
ffi.cast("void (**)(void)", listener), data)
end,
set_user_data=function(wl_buffer,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_buffer), user_data)
end,
get_user_data=function(wl_buffer)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_buffer))
end,
get_version=function(wl_buffer)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_buffer))
end,
destroy=function(wl_buffer
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_buffer)
,0
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_buffer))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_buffer.interface)
ffi.cdef[=[
struct wl_data_offer_listener {
void (*offer)(
void *data,
struct wl_data_offer *wl_data_offer
,const char* mime_type
);
void (*source_actions)(
void *data,
struct wl_data_offer *wl_data_offer
,uint32_t source_actions
);
void (*action)(
void *data,
struct wl_data_offer *wl_data_offer
,uint32_t dnd_action
);
};
]=]
M.wl_data_offer={
add_listener=function(wl_data_offer,listener,data)
return wayland.wl_proxy_add_listener(
ffi.cast("struct wl_proxy *", wl_data_offer),
ffi.cast("void (**)(void)", listener), data)
end,
error={
invalid_finish = 0,
invalid_action_mask = 1,
invalid_action = 2,
invalid_offer = 3,
},
set_user_data=function(wl_data_offer,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_data_offer), user_data)
end,
get_user_data=function(wl_data_offer)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_data_offer))
end,
get_version=function(wl_data_offer)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_data_offer))
end,
accept=function(wl_data_offer
,serial
,mime_type
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_data_offer)
,0
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_data_offer))
, 0
, serial
, mime_type
)
end,
receive=function(wl_data_offer
,mime_type
,fd
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_data_offer)
,1
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_data_offer))
, 0
, mime_type
, fd
)
end,
destroy=function(wl_data_offer
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_data_offer)
,2
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_data_offer))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
finish=function(wl_data_offer
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_data_offer)
,3
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_data_offer))
, 0
)
end,
set_actions=function(wl_data_offer
,dnd_actions
,preferred_action
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_data_offer)
,4
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_data_offer))
, 0
, dnd_actions
, preferred_action
)
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_data_offer.interface)
ffi.cdef[=[
struct wl_data_source_listener {
void (*target)(
void *data,
struct wl_data_source *wl_data_source
,const char* mime_type
);
void (*send)(
void *data,
struct wl_data_source *wl_data_source
,const char* mime_type
,int32_t fd
);
void (*cancelled)(
void *data,
struct wl_data_source *wl_data_source
);
void (*dnd_drop_performed)(
void *data,
struct wl_data_source *wl_data_source
);
void (*dnd_finished)(
void *data,
struct wl_data_source *wl_data_source
);
void (*action)(
void *data,
struct wl_data_source *wl_data_source
,uint32_t dnd_action
);
};
]=]
M.wl_data_source={
add_listener=function(wl_data_source,listener,data)
return wayland.wl_proxy_add_listener(
ffi.cast("struct wl_proxy *", wl_data_source),
ffi.cast("void (**)(void)", listener), data)
end,
error={
invalid_action_mask = 0,
invalid_source = 1,
},
set_user_data=function(wl_data_source,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_data_source), user_data)
end,
get_user_data=function(wl_data_source)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_data_source))
end,
get_version=function(wl_data_source)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_data_source))
end,
offer=function(wl_data_source
,mime_type
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_data_source)
,0
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_data_source))
, 0
, mime_type
)
end,
destroy=function(wl_data_source
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_data_source)
,1
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_data_source))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
set_actions=function(wl_data_source
,dnd_actions
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_data_source)
,2
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_data_source))
, 0
, dnd_actions
)
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_data_source.interface)
ffi.cdef[=[
struct wl_data_device_listener {
void (*data_offer)(
void *data,
struct wl_data_device *wl_data_device
,struct wl_data_offer* id
);
void (*enter)(
void *data,
struct wl_data_device *wl_data_device
,uint32_t serial
,struct wl_surface* surface
,wl_fixed_t x
,wl_fixed_t y
,struct wl_data_offer* id
);
void (*leave)(
void *data,
struct wl_data_device *wl_data_device
);
void (*motion)(
void *data,
struct wl_data_device *wl_data_device
,uint32_t time
,wl_fixed_t x
,wl_fixed_t y
);
void (*drop)(
void *data,
struct wl_data_device *wl_data_device
);
void (*selection)(
void *data,
struct wl_data_device *wl_data_device
,struct wl_data_offer* id
);
};
]=]
M.wl_data_device={
add_listener=function(wl_data_device,listener,data)
return wayland.wl_proxy_add_listener(
ffi.cast("struct wl_proxy *", wl_data_device),
ffi.cast("void (**)(void)", listener), data)
end,
error={
role = 0,
used_source = 1,
},
set_user_data=function(wl_data_device,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_data_device), user_data)
end,
get_user_data=function(wl_data_device)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_data_device))
end,
get_version=function(wl_data_device)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_data_device))
end,
start_drag=function(wl_data_device
,source
,origin
,icon
,serial
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_data_device)
,0
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_data_device))
, 0
, source
, origin
, icon
, serial
)
end,
set_selection=function(wl_data_device
,source
,serial
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_data_device)
,1
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_data_device))
, 0
, source
, serial
)
end,
release=function(wl_data_device
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_data_device)
,2
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_data_device))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_data_device.interface)
M.wl_data_device_manager={
dnd_action={
none = 0,
copy = 1,
move = 2,
ask = 4,
},
set_user_data=function(wl_data_device_manager,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_data_device_manager), user_data)
end,
get_user_data=function(wl_data_device_manager)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_data_device_manager))
end,
get_version=function(wl_data_device_manager)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_data_device_manager))
end,
create_data_source=function(wl_data_device_manager
)
return ffi.cast("struct wl_data_source *",
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_data_device_manager)
,0
,M.wl_data_source.interface
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_data_device_manager))
, 0
, id
)
)
end,
get_data_device=function(wl_data_device_manager
,seat
)
return ffi.cast("struct wl_data_device *",
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_data_device_manager)
,1
,M.wl_data_device.interface
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_data_device_manager))
, 0
, id
, seat
)
)
end,
release=function(wl_data_device_manager
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_data_device_manager)
,2
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_data_device_manager))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_data_device_manager.interface)
M.wl_shell={
error={
role = 0,
},
set_user_data=function(wl_shell,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_shell), user_data)
end,
get_user_data=function(wl_shell)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_shell))
end,
get_version=function(wl_shell)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_shell))
end,
destroy=function(wl_shell)
return wayland.wl_proxy_destroy(
ffi.cast("struct wl_proxy *", wl_shell))
end,
get_shell_surface=function(wl_shell
,surface
)
return ffi.cast("struct wl_shell_surface *",
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_shell)
,0
,M.wl_shell_surface.interface
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_shell))
, 0
, id
, surface
)
)
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_shell.interface)
ffi.cdef[=[
struct wl_shell_surface_listener {
void (*ping)(
void *data,
struct wl_shell_surface *wl_shell_surface
,uint32_t serial
);
void (*configure)(
void *data,
struct wl_shell_surface *wl_shell_surface
,uint32_t edges
,int32_t width
,int32_t height
);
void (*popup_done)(
void *data,
struct wl_shell_surface *wl_shell_surface
);
};
]=]
M.wl_shell_surface={
add_listener=function(wl_shell_surface,listener,data)
return wayland.wl_proxy_add_listener(
ffi.cast("struct wl_proxy *", wl_shell_surface),
ffi.cast("void (**)(void)", listener), data)
end,
resize={
none = 0,
top = 1,
bottom = 2,
left = 4,
top_left = 5,
bottom_left = 6,
right = 8,
top_right = 9,
bottom_right = 10,
},
transient={
inactive = 1,
},
fullscreen_method={
default = 0,
scale = 1,
driver = 2,
fill = 3,
},
set_user_data=function(wl_shell_surface,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_shell_surface), user_data)
end,
get_user_data=function(wl_shell_surface)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_shell_surface))
end,
get_version=function(wl_shell_surface)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_shell_surface))
end,
destroy=function(wl_shell_surface)
return wayland.wl_proxy_destroy(
ffi.cast("struct wl_proxy *", wl_shell_surface))
end,
pong=function(wl_shell_surface
,serial
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_shell_surface)
,0
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_shell_surface))
, 0
, serial
)
end,
move=function(wl_shell_surface
,seat
,serial
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_shell_surface)
,1
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_shell_surface))
, 0
, seat
, serial
)
end,
resize=function(wl_shell_surface
,seat
,serial
,edges
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_shell_surface)
,2
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_shell_surface))
, 0
, seat
, serial
, edges
)
end,
set_toplevel=function(wl_shell_surface
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_shell_surface)
,3
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_shell_surface))
, 0
)
end,
set_transient=function(wl_shell_surface
,parent
,x
,y
,flags
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_shell_surface)
,4
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_shell_surface))
, 0
, parent
, x
, y
, flags
)
end,
set_fullscreen=function(wl_shell_surface
,method
,framerate
,output
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_shell_surface)
,5
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_shell_surface))
, 0
, method
, framerate
, output
)
end,
set_popup=function(wl_shell_surface
,seat
,serial
,parent
,x
,y
,flags
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_shell_surface)
,6
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_shell_surface))
, 0
, seat
, serial
, parent
, x
, y
, flags
)
end,
set_maximized=function(wl_shell_surface
,output
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_shell_surface)
,7
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_shell_surface))
, 0
, output
)
end,
set_title=function(wl_shell_surface
,title
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_shell_surface)
,8
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_shell_surface))
, 0
, title
)
end,
set_class=function(wl_shell_surface
,class_
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_shell_surface)
,9
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_shell_surface))
, 0
, class_
)
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_shell_surface.interface)
ffi.cdef[=[
struct wl_surface_listener {
void (*enter)(
void *data,
struct wl_surface *wl_surface
,struct wl_output* output
);
void (*leave)(
void *data,
struct wl_surface *wl_surface
,struct wl_output* output
);
void (*preferred_buffer_scale)(
void *data,
struct wl_surface *wl_surface
,int32_t factor
);
void (*preferred_buffer_transform)(
void *data,
struct wl_surface *wl_surface
,uint32_t transform
);
};
]=]
M.wl_surface={
add_listener=function(wl_surface,listener,data)
return wayland.wl_proxy_add_listener(
ffi.cast("struct wl_proxy *", wl_surface),
ffi.cast("void (**)(void)", listener), data)
end,
error={
invalid_scale = 0,
invalid_transform = 1,
invalid_size = 2,
invalid_offset = 3,
defunct_role_object = 4,
no_buffer = 5,
},
set_user_data=function(wl_surface,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_surface), user_data)
end,
get_user_data=function(wl_surface)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_surface))
end,
get_version=function(wl_surface)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_surface))
end,
destroy=function(wl_surface
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_surface)
,0
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_surface))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
attach=function(wl_surface
,buffer
,x
,y
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_surface)
,1
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_surface))
, 0
, buffer
, x
, y
)
end,
damage=function(wl_surface
,x
,y
,width
,height
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_surface)
,2
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_surface))
, 0
, x
, y
, width
, height
)
end,
frame=function(wl_surface
)
return ffi.cast("struct wl_callback *",
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_surface)
,3
,M.wl_callback.interface
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_surface))
, 0
, callback
)
)
end,
set_opaque_region=function(wl_surface
,region
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_surface)
,4
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_surface))
, 0
, region
)
end,
set_input_region=function(wl_surface
,region
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_surface)
,5
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_surface))
, 0
, region
)
end,
commit=function(wl_surface
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_surface)
,6
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_surface))
, 0
)
end,
set_buffer_transform=function(wl_surface
,transform
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_surface)
,7
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_surface))
, 0
, transform
)
end,
set_buffer_scale=function(wl_surface
,scale
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_surface)
,8
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_surface))
, 0
, scale
)
end,
damage_buffer=function(wl_surface
,x
,y
,width
,height
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_surface)
,9
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_surface))
, 0
, x
, y
, width
, height
)
end,
offset=function(wl_surface
,x
,y
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_surface)
,10
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_surface))
, 0
, x
, y
)
end,
get_release=function(wl_surface
)
return ffi.cast("struct wl_callback *",
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_surface)
,11
,M.wl_callback.interface
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_surface))
, 0
, callback
)
)
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_surface.interface)
ffi.cdef[=[
struct wl_seat_listener {
void (*capabilities)(
void *data,
struct wl_seat *wl_seat
,uint32_t capabilities
);
void (*name)(
void *data,
struct wl_seat *wl_seat
,const char* name
);
};
]=]
M.wl_seat={
add_listener=function(wl_seat,listener,data)
return wayland.wl_proxy_add_listener(
ffi.cast("struct wl_proxy *", wl_seat),
ffi.cast("void (**)(void)", listener), data)
end,
capability={
pointer = 1,
keyboard = 2,
touch = 4,
},
error={
missing_capability = 0,
},
set_user_data=function(wl_seat,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_seat), user_data)
end,
get_user_data=function(wl_seat)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_seat))
end,
get_version=function(wl_seat)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_seat))
end,
get_pointer=function(wl_seat
)
return ffi.cast("struct wl_pointer *",
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_seat)
,0
,M.wl_pointer.interface
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_seat))
, 0
, id
)
)
end,
get_keyboard=function(wl_seat
)
return ffi.cast("struct wl_keyboard *",
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_seat)
,1
,M.wl_keyboard.interface
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_seat))
, 0
, id
)
)
end,
get_touch=function(wl_seat
)
return ffi.cast("struct wl_touch *",
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_seat)
,2
,M.wl_touch.interface
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_seat))
, 0
, id
)
)
end,
release=function(wl_seat
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_seat)
,3
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_seat))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_seat.interface)
ffi.cdef[=[
struct wl_pointer_listener {
void (*enter)(
void *data,
struct wl_pointer *wl_pointer
,uint32_t serial
,struct wl_surface* surface
,wl_fixed_t surface_x
,wl_fixed_t surface_y
);
void (*leave)(
void *data,
struct wl_pointer *wl_pointer
,uint32_t serial
,struct wl_surface* surface
);
void (*motion)(
void *data,
struct wl_pointer *wl_pointer
,uint32_t time
,wl_fixed_t surface_x
,wl_fixed_t surface_y
);
void (*button)(
void *data,
struct wl_pointer *wl_pointer
,uint32_t serial
,uint32_t time
,uint32_t button
,uint32_t state
);
void (*axis)(
void *data,
struct wl_pointer *wl_pointer
,uint32_t time
,uint32_t axis
,wl_fixed_t value
);
void (*frame)(
void *data,
struct wl_pointer *wl_pointer
);
void (*axis_source)(
void *data,
struct wl_pointer *wl_pointer
,uint32_t axis_source
);
void (*axis_stop)(
void *data,
struct wl_pointer *wl_pointer
,uint32_t time
,uint32_t axis
);
void (*axis_discrete)(
void *data,
struct wl_pointer *wl_pointer
,uint32_t axis
,int32_t discrete
);
void (*axis_value120)(
void *data,
struct wl_pointer *wl_pointer
,uint32_t axis
,int32_t value120
);
void (*axis_relative_direction)(
void *data,
struct wl_pointer *wl_pointer
,uint32_t axis
,uint32_t direction
);
};
]=]
M.wl_pointer={
add_listener=function(wl_pointer,listener,data)
return wayland.wl_proxy_add_listener(
ffi.cast("struct wl_proxy *", wl_pointer),
ffi.cast("void (**)(void)", listener), data)
end,
error={
role = 0,
},
button_state={
released = 0,
pressed = 1,
},
axis={
vertical_scroll = 0,
horizontal_scroll = 1,
},
axis_source={
wheel = 0,
finger = 1,
continuous = 2,
wheel_tilt = 3,
},
axis_relative_direction={
identical = 0,
inverted = 1,
},
set_user_data=function(wl_pointer,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_pointer), user_data)
end,
get_user_data=function(wl_pointer)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_pointer))
end,
get_version=function(wl_pointer)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_pointer))
end,
set_cursor=function(wl_pointer
,serial
,surface
,hotspot_x
,hotspot_y
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_pointer)
,0
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_pointer))
, 0
, serial
, surface
, hotspot_x
, hotspot_y
)
end,
release=function(wl_pointer
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_pointer)
,1
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_pointer))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_pointer.interface)
ffi.cdef[=[
struct wl_keyboard_listener {
void (*keymap)(
void *data,
struct wl_keyboard *wl_keyboard
,uint32_t format
,int32_t fd
,uint32_t size
);
void (*enter)(
void *data,
struct wl_keyboard *wl_keyboard
,uint32_t serial
,struct wl_surface* surface
,struct wl_array* keys
);
void (*leave)(
void *data,
struct wl_keyboard *wl_keyboard
,uint32_t serial
,struct wl_surface* surface
);
void (*key)(
void *data,
struct wl_keyboard *wl_keyboard
,uint32_t serial
,uint32_t time
,uint32_t key
,uint32_t state
);
void (*modifiers)(
void *data,
struct wl_keyboard *wl_keyboard
,uint32_t serial
,uint32_t mods_depressed
,uint32_t mods_latched
,uint32_t mods_locked
,uint32_t group
);
void (*repeat_info)(
void *data,
struct wl_keyboard *wl_keyboard
,int32_t rate
,int32_t delay
);
};
]=]
M.wl_keyboard={
add_listener=function(wl_keyboard,listener,data)
return wayland.wl_proxy_add_listener(
ffi.cast("struct wl_proxy *", wl_keyboard),
ffi.cast("void (**)(void)", listener), data)
end,
keymap_format={
no_keymap = 0,
xkb_v1 = 1,
},
key_state={
released = 0,
pressed = 1,
repeated = 2,
},
set_user_data=function(wl_keyboard,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_keyboard), user_data)
end,
get_user_data=function(wl_keyboard)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_keyboard))
end,
get_version=function(wl_keyboard)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_keyboard))
end,
release=function(wl_keyboard
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_keyboard)
,0
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_keyboard))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_keyboard.interface)
ffi.cdef[=[
struct wl_touch_listener {
void (*down)(
void *data,
struct wl_touch *wl_touch
,uint32_t serial
,uint32_t time
,struct wl_surface* surface
,int32_t id
,wl_fixed_t x
,wl_fixed_t y
);
void (*up)(
void *data,
struct wl_touch *wl_touch
,uint32_t serial
,uint32_t time
,int32_t id
);
void (*motion)(
void *data,
struct wl_touch *wl_touch
,uint32_t time
,int32_t id
,wl_fixed_t x
,wl_fixed_t y
);
void (*frame)(
void *data,
struct wl_touch *wl_touch
);
void (*cancel)(
void *data,
struct wl_touch *wl_touch
);
void (*shape)(
void *data,
struct wl_touch *wl_touch
,int32_t id
,wl_fixed_t major
,wl_fixed_t minor
);
void (*orientation)(
void *data,
struct wl_touch *wl_touch
,int32_t id
,wl_fixed_t orientation
);
};
]=]
M.wl_touch={
add_listener=function(wl_touch,listener,data)
return wayland.wl_proxy_add_listener(
ffi.cast("struct wl_proxy *", wl_touch),
ffi.cast("void (**)(void)", listener), data)
end,
set_user_data=function(wl_touch,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_touch), user_data)
end,
get_user_data=function(wl_touch)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_touch))
end,
get_version=function(wl_touch)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_touch))
end,
release=function(wl_touch
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_touch)
,0
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_touch))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_touch.interface)
ffi.cdef[=[
struct wl_output_listener {
void (*geometry)(
void *data,
struct wl_output *wl_output
,int32_t x
,int32_t y
,int32_t physical_width
,int32_t physical_height
,int32_t subpixel
,const char* make
,const char* model
,int32_t transform
);
void (*mode)(
void *data,
struct wl_output *wl_output
,uint32_t flags
,int32_t width
,int32_t height
,int32_t refresh
);
void (*done)(
void *data,
struct wl_output *wl_output
);
void (*scale)(
void *data,
struct wl_output *wl_output
,int32_t factor
);
void (*name)(
void *data,
struct wl_output *wl_output
,const char* name
);
void (*description)(
void *data,
struct wl_output *wl_output
,const char* description
);
};
]=]
M.wl_output={
add_listener=function(wl_output,listener,data)
return wayland.wl_proxy_add_listener(
ffi.cast("struct wl_proxy *", wl_output),
ffi.cast("void (**)(void)", listener), data)
end,
subpixel={
unknown = 0,
none = 1,
horizontal_rgb = 2,
horizontal_bgr = 3,
vertical_rgb = 4,
vertical_bgr = 5,
},
transform={
normal = 0,
["90"] = 1,
["180"] = 2,
["270"] = 3,
flipped = 4,
flipped_90 = 5,
flipped_180 = 6,
flipped_270 = 7,
},
mode={
current = 1,
preferred = 2,
},
set_user_data=function(wl_output,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_output), user_data)
end,
get_user_data=function(wl_output)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_output))
end,
get_version=function(wl_output)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_output))
end,
release=function(wl_output
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_output)
,0
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_output))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_output.interface)
M.wl_region={
set_user_data=function(wl_region,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_region), user_data)
end,
get_user_data=function(wl_region)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_region))
end,
get_version=function(wl_region)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_region))
end,
destroy=function(wl_region
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_region)
,0
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_region))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
add=function(wl_region
,x
,y
,width
,height
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_region)
,1
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_region))
, 0
, x
, y
, width
, height
)
end,
subtract=function(wl_region
,x
,y
,width
,height
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_region)
,2
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_region))
, 0
, x
, y
, width
, height
)
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_region.interface)
M.wl_subcompositor={
error={
bad_surface = 0,
bad_parent = 1,
},
set_user_data=function(wl_subcompositor,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_subcompositor), user_data)
end,
get_user_data=function(wl_subcompositor)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_subcompositor))
end,
get_version=function(wl_subcompositor)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_subcompositor))
end,
destroy=function(wl_subcompositor
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_subcompositor)
,0
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_subcompositor))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
get_subsurface=function(wl_subcompositor
,surface
,parent
)
return ffi.cast("struct wl_subsurface *",
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_subcompositor)
,1
,M.wl_subsurface.interface
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_subcompositor))
, 0
, id
, surface
, parent
)
)
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_subcompositor.interface)
M.wl_subsurface={
error={
bad_surface = 0,
},
set_user_data=function(wl_subsurface,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_subsurface), user_data)
end,
get_user_data=function(wl_subsurface)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_subsurface))
end,
get_version=function(wl_subsurface)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_subsurface))
end,
destroy=function(wl_subsurface
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_subsurface)
,0
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_subsurface))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
set_position=function(wl_subsurface
,x
,y
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_subsurface)
,1
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_subsurface))
, 0
, x
, y
)
end,
place_above=function(wl_subsurface
,sibling
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_subsurface)
,2
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_subsurface))
, 0
, sibling
)
end,
place_below=function(wl_subsurface
,sibling
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_subsurface)
,3
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_subsurface))
, 0
, sibling
)
end,
set_sync=function(wl_subsurface
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_subsurface)
,4
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_subsurface))
, 0
)
end,
set_desync=function(wl_subsurface
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_subsurface)
,5
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_subsurface))
, 0
)
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_subsurface.interface)
M.wl_fixes={
error={
invalid_ack_remove = 0,
},
set_user_data=function(wl_fixes,user_data)
wayland.wl_proxy_set_user_data(
ffi.cast("struct wl_proxy *", wl_fixes), user_data)
end,
get_user_data=function(wl_fixes)
return wayland.wl_proxy_get_user_data(
ffi.cast("struct wl_proxy *", wl_fixes))
end,
get_version=function(wl_fixes)
return wayland.wl_proxy_get_version(
ffi.cast("struct wl_proxy *", wl_fixes))
end,
destroy=function(wl_fixes
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_fixes)
,0
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_fixes))
, wayland.WL_MARSHAL_FLAG_DESTROY
)
end,
destroy_registry=function(wl_fixes
,registry
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_fixes)
,1
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_fixes))
, 0
, registry
)
end,
ack_global_remove=function(wl_fixes
,registry
,name
)
wayland.wl_proxy_marshal_flags(
ffi.cast("struct wl_proxy *", wl_fixes)
,2
,nil
, wl_proxy_get_version(ffi.cast("struct wl_proxy *", wl_fixes))
, 0
, registry
, name
)
end,
interface=ffi.new("struct wl_interface[1]")
}
M.interface_ptr=ffi.cast("struct wl_interface*",M.wl_fixes.interface)
local args_types_wl_compositor_create_region=ffi.new("const struct wl_interface*[1]",{
M.wl_region.interface_ptr,
})
local args_types_wl_compositor_create_surface=ffi.new("const struct wl_interface*[1]",{
M.wl_surface.interface_ptr,
})
local args_types_wl_data_device_data_offer=ffi.new("const struct wl_interface*[1]",{
M.wl_data_offer.interface_ptr,
})
local args_types_wl_data_device_enter=ffi.new("const struct wl_interface*[5]",{
nil,
M.wl_surface.interface_ptr,
nil,
nil,
M.wl_data_offer.interface_ptr,
})
local args_types_wl_data_device_selection=ffi.new("const struct wl_interface*[1]",{
M.wl_data_offer.interface_ptr,
})
local args_types_wl_data_device_set_selection=ffi.new("const struct wl_interface*[2]",{
M.wl_data_source.interface_ptr,
nil,
})
local args_types_wl_data_device_start_drag=ffi.new("const struct wl_interface*[4]",{
M.wl_data_source.interface_ptr,
M.wl_surface.interface_ptr,
M.wl_surface.interface_ptr,
nil,
})
local args_types_wl_data_device_manager_create_data_source=ffi.new("const struct wl_interface*[1]",{
M.wl_data_source.interface_ptr,
})
local args_types_wl_data_device_manager_get_data_device=ffi.new("const struct wl_interface*[2]",{
M.wl_data_device.interface_ptr,
M.wl_seat.interface_ptr,
})
local args_types_wl_display_get_registry=ffi.new("const struct wl_interface*[1]",{
M.wl_registry.interface_ptr,
})
local args_types_wl_display_sync=ffi.new("const struct wl_interface*[1]",{
M.wl_callback.interface_ptr,
})
local args_types_wl_fixes_ack_global_remove=ffi.new("const struct wl_interface*[2]",{
M.wl_registry.interface_ptr,
nil,
})
local args_types_wl_fixes_destroy_registry=ffi.new("const struct wl_interface*[1]",{
M.wl_registry.interface_ptr,
})
local args_types_wl_keyboard_enter=ffi.new("const struct wl_interface*[3]",{
nil,
M.wl_surface.interface_ptr,
nil,
})
local args_types_wl_keyboard_leave=ffi.new("const struct wl_interface*[2]",{
nil,
M.wl_surface.interface_ptr,
})
local args_types_wl_pointer_enter=ffi.new("const struct wl_interface*[4]",{
nil,
M.wl_surface.interface_ptr,
nil,
nil,
})
local args_types_wl_pointer_leave=ffi.new("const struct wl_interface*[2]",{
nil,
M.wl_surface.interface_ptr,
})
local args_types_wl_pointer_set_cursor=ffi.new("const struct wl_interface*[4]",{
nil,
M.wl_surface.interface_ptr,
nil,
nil,
})
local args_types_wl_seat_get_keyboard=ffi.new("const struct wl_interface*[1]",{
M.wl_keyboard.interface_ptr,
})
local args_types_wl_seat_get_pointer=ffi.new("const struct wl_interface*[1]",{
M.wl_pointer.interface_ptr,
})
local args_types_wl_seat_get_touch=ffi.new("const struct wl_interface*[1]",{
M.wl_touch.interface_ptr,
})
local args_types_wl_shell_get_shell_surface=ffi.new("const struct wl_interface*[2]",{
M.wl_shell_surface.interface_ptr,
M.wl_surface.interface_ptr,
})
local args_types_wl_shell_surface_move=ffi.new("const struct wl_interface*[2]",{
M.wl_seat.interface_ptr,
nil,
})
local args_types_wl_shell_surface_resize=ffi.new("const struct wl_interface*[3]",{
M.wl_seat.interface_ptr,
nil,
nil,
})
local args_types_wl_shell_surface_set_fullscreen=ffi.new("const struct wl_interface*[3]",{
nil,
nil,
M.wl_output.interface_ptr,
})
local args_types_wl_shell_surface_set_maximized=ffi.new("const struct wl_interface*[1]",{
M.wl_output.interface_ptr,
})
local args_types_wl_shell_surface_set_popup=ffi.new("const struct wl_interface*[6]",{
M.wl_seat.interface_ptr,
nil,
M.wl_surface.interface_ptr,
nil,
nil,
nil,
})
local args_types_wl_shell_surface_set_transient=ffi.new("const struct wl_interface*[4]",{
M.wl_surface.interface_ptr,
nil,
nil,
nil,
})
local args_types_wl_shm_create_pool=ffi.new("const struct wl_interface*[3]",{
M.wl_shm_pool.interface_ptr,
nil,
nil,
})
local args_types_wl_shm_pool_create_buffer=ffi.new("const struct wl_interface*[6]",{
M.wl_buffer.interface_ptr,
nil,
nil,
nil,
nil,
nil,
})
local args_types_wl_subcompositor_get_subsurface=ffi.new("const struct wl_interface*[3]",{
M.wl_subsurface.interface_ptr,
M.wl_surface.interface_ptr,
M.wl_surface.interface_ptr,
})
local args_types_wl_subsurface_place_above=ffi.new("const struct wl_interface*[1]",{
M.wl_surface.interface_ptr,
})
local args_types_wl_subsurface_place_below=ffi.new("const struct wl_interface*[1]",{
M.wl_surface.interface_ptr,
})
local args_types_wl_surface_attach=ffi.new("const struct wl_interface*[3]",{
M.wl_buffer.interface_ptr,
nil,
nil,
})
local args_types_wl_surface_enter=ffi.new("const struct wl_interface*[1]",{
M.wl_output.interface_ptr,
})
local args_types_wl_surface_frame=ffi.new("const struct wl_interface*[1]",{
M.wl_callback.interface_ptr,
})
local args_types_wl_surface_get_release=ffi.new("const struct wl_interface*[1]",{
M.wl_callback.interface_ptr,
})
local args_types_wl_surface_leave=ffi.new("const struct wl_interface*[1]",{
M.wl_output.interface_ptr,
})
local args_types_wl_surface_set_input_region=ffi.new("const struct wl_interface*[1]",{
M.wl_region.interface_ptr,
})
local args_types_wl_surface_set_opaque_region=ffi.new("const struct wl_interface*[1]",{
M.wl_region.interface_ptr,
})
local args_types_wl_touch_down=ffi.new("const struct wl_interface*[6]",{
nil,
nil,
M.wl_surface.interface_ptr,
nil,
nil,
nil,
})
local args_types_nil=ffi.new("const struct wl_interface*[8]",{
nil,
nil,
nil,
nil,
nil,
nil,
nil,
nil,
})
local wl_display_requests=ffi.new("struct wl_message[2]",{
{"sync",
"n",
args_types_wl_display_sync
},
{"get_registry",
"n",
args_types_wl_display_get_registry
},
})
local wl_display_events=ffi.new("struct wl_message[2]",{
{"error",
"ous",
args_types_nil
},
{"delete_id",
"u",
args_types_nil
},
})
M.wl_display.interface[0].name=wl_display
M.wl_display.interface[0].version=1
M.wl_display.interface[0].method_count=2
M.wl_display.interface[0].methods=wl_display_requests
M.wl_display.interface[0].event_count=2
M.wl_display.interface[0].events=wl_display_events
local wl_registry_requests=ffi.new("struct wl_message[1]",{
{"bind",
"usun",
args_types_nil
},
})
local wl_registry_events=ffi.new("struct wl_message[2]",{
{"global",
"usu",
args_types_nil
},
{"global_remove",
"u",
args_types_nil
},
})
M.wl_registry.interface[0].name=wl_registry
M.wl_registry.interface[0].version=1
M.wl_registry.interface[0].method_count=1
M.wl_registry.interface[0].methods=wl_registry_requests
M.wl_registry.interface[0].event_count=2
M.wl_registry.interface[0].events=wl_registry_events
local wl_callback_events=ffi.new("struct wl_message[1]",{
{"done",
"u",
args_types_nil
},
})
M.wl_callback.interface[0].name=wl_callback
M.wl_callback.interface[0].version=1
M.wl_callback.interface[0].method_count=0
M.wl_callback.interface[0].methods=nil
M.wl_callback.interface[0].event_count=1
M.wl_callback.interface[0].events=nil
local wl_compositor_requests=ffi.new("struct wl_message[3]",{
{"create_surface",
"n",
args_types_wl_compositor_create_surface
},
{"create_region",
"n",
args_types_wl_compositor_create_region
},
{"release",
"7",
args_types_nil
},
})
M.wl_compositor.interface[0].name=wl_compositor
M.wl_compositor.interface[0].version=7
M.wl_compositor.interface[0].method_count=3
M.wl_compositor.interface[0].methods=wl_compositor_requests
M.wl_compositor.interface[0].event_count=0
M.wl_compositor.interface[0].events=wl_compositor_events
local wl_shm_pool_requests=ffi.new("struct wl_message[3]",{
{"create_buffer",
"niiiiu",
args_types_wl_shm_pool_create_buffer
},
{"destroy",
"",
args_types_nil
},
{"resize",
"i",
args_types_nil
},
})
M.wl_shm_pool.interface[0].name=wl_shm_pool
M.wl_shm_pool.interface[0].version=2
M.wl_shm_pool.interface[0].method_count=3
M.wl_shm_pool.interface[0].methods=wl_shm_pool_requests
M.wl_shm_pool.interface[0].event_count=0
M.wl_shm_pool.interface[0].events=wl_shm_pool_events
local wl_shm_requests=ffi.new("struct wl_message[2]",{
{"create_pool",
"nhi",
args_types_wl_shm_create_pool
},
{"release",
"2",
args_types_nil
},
})
local wl_shm_events=ffi.new("struct wl_message[1]",{
{"format",
"u",
args_types_nil
},
})
M.wl_shm.interface[0].name=wl_shm
M.wl_shm.interface[0].version=2
M.wl_shm.interface[0].method_count=2
M.wl_shm.interface[0].methods=wl_shm_requests
M.wl_shm.interface[0].event_count=1
M.wl_shm.interface[0].events=wl_shm_events
local wl_buffer_requests=ffi.new("struct wl_message[1]",{
{"destroy",
"",
args_types_nil
},
})
local wl_buffer_events=ffi.new("struct wl_message[1]",{
{"release",
"",
args_types_nil
},
})
M.wl_buffer.interface[0].name=wl_buffer
M.wl_buffer.interface[0].version=1
M.wl_buffer.interface[0].method_count=1
M.wl_buffer.interface[0].methods=wl_buffer_requests
M.wl_buffer.interface[0].event_count=1
M.wl_buffer.interface[0].events=wl_buffer_events
local wl_data_offer_requests=ffi.new("struct wl_message[5]",{
{"accept",
"u?s",
args_types_nil
},
{"receive",
"sh",
args_types_nil
},
{"destroy",
"",
args_types_nil
},
{"finish",
"3",
args_types_nil
},
{"set_actions",
"3uu",
args_types_nil
},
})
local wl_data_offer_events=ffi.new("struct wl_message[3]",{
{"offer",
"s",
args_types_nil
},
{"source_actions",
"3u",
args_types_nil
},
{"action",
"3u",
args_types_nil
},
})
M.wl_data_offer.interface[0].name=wl_data_offer
M.wl_data_offer.interface[0].version=4
M.wl_data_offer.interface[0].method_count=5
M.wl_data_offer.interface[0].methods=wl_data_offer_requests
M.wl_data_offer.interface[0].event_count=3
M.wl_data_offer.interface[0].events=wl_data_offer_events
local wl_data_source_requests=ffi.new("struct wl_message[3]",{
{"offer",
"s",
args_types_nil
},
{"destroy",
"",
args_types_nil
},
{"set_actions",
"3u",
args_types_nil
},
})
local wl_data_source_events=ffi.new("struct wl_message[6]",{
{"target",
"?s",
args_types_nil
},
{"send",
"sh",
args_types_nil
},
{"cancelled",
"",
args_types_nil
},
{"dnd_drop_performed",
"3",
args_types_nil
},
{"dnd_finished",
"3",
args_types_nil
},
{"action",
"3u",
args_types_nil
},
})
M.wl_data_source.interface[0].name=wl_data_source
M.wl_data_source.interface[0].version=4
M.wl_data_source.interface[0].method_count=3
M.wl_data_source.interface[0].methods=wl_data_source_requests
M.wl_data_source.interface[0].event_count=6
M.wl_data_source.interface[0].events=wl_data_source_events
local wl_data_device_requests=ffi.new("struct wl_message[3]",{
{"start_drag",
"?oo?ou",
args_types_wl_data_device_start_drag
},
{"set_selection",
"?ou",
args_types_wl_data_device_set_selection
},
{"release",
"2",
args_types_nil
},
})
local wl_data_device_events=ffi.new("struct wl_message[6]",{
{"data_offer",
"n",
args_types_wl_data_device_data_offer
},
{"enter",
"uoff?o",
args_types_wl_data_device_enter
},
{"leave",
"",
args_types_nil
},
{"motion",
"uff",
args_types_nil
},
{"drop",
"",
args_types_nil
},
{"selection",
"?o",
args_types_wl_data_device_selection
},
})
M.wl_data_device.interface[0].name=wl_data_device
M.wl_data_device.interface[0].version=4
M.wl_data_device.interface[0].method_count=3
M.wl_data_device.interface[0].methods=wl_data_device_requests
M.wl_data_device.interface[0].event_count=6
M.wl_data_device.interface[0].events=wl_data_device_events
local wl_data_device_manager_requests=ffi.new("struct wl_message[3]",{
{"create_data_source",
"n",
args_types_wl_data_device_manager_create_data_source
},
{"get_data_device",
"no",
args_types_wl_data_device_manager_get_data_device
},
{"release",
"4",
args_types_nil
},
})
M.wl_data_device_manager.interface[0].name=wl_data_device_manager
M.wl_data_device_manager.interface[0].version=4
M.wl_data_device_manager.interface[0].method_count=3
M.wl_data_device_manager.interface[0].methods=wl_data_device_manager_requests
M.wl_data_device_manager.interface[0].event_count=0
M.wl_data_device_manager.interface[0].events=wl_data_device_manager_events
local wl_shell_requests=ffi.new("struct wl_message[1]",{
{"get_shell_surface",
"no",
args_types_wl_shell_get_shell_surface
},
})
M.wl_shell.interface[0].name=wl_shell
M.wl_shell.interface[0].version=1
M.wl_shell.interface[0].method_count=1
M.wl_shell.interface[0].methods=wl_shell_requests
M.wl_shell.interface[0].event_count=0
M.wl_shell.interface[0].events=wl_shell_events
local wl_shell_surface_requests=ffi.new("struct wl_message[10]",{
{"pong",
"u",
args_types_nil
},
{"move",
"ou",
args_types_wl_shell_surface_move
},
{"resize",
"ouu",
args_types_wl_shell_surface_resize
},
{"set_toplevel",
"",
args_types_nil
},
{"set_transient",
"oiiu",
args_types_wl_shell_surface_set_transient
},
{"set_fullscreen",
"uu?o",
args_types_wl_shell_surface_set_fullscreen
},
{"set_popup",
"ouoiiu",
args_types_wl_shell_surface_set_popup
},
{"set_maximized",
"?o",
args_types_wl_shell_surface_set_maximized
},
{"set_title",
"s",
args_types_nil
},
{"set_class",
"s",
args_types_nil
},
})
local wl_shell_surface_events=ffi.new("struct wl_message[3]",{
{"ping",
"u",
args_types_nil
},
{"configure",
"uii",
args_types_nil
},
{"popup_done",
"",
args_types_nil
},
})
M.wl_shell_surface.interface[0].name=wl_shell_surface
M.wl_shell_surface.interface[0].version=1
M.wl_shell_surface.interface[0].method_count=10
M.wl_shell_surface.interface[0].methods=wl_shell_surface_requests
M.wl_shell_surface.interface[0].event_count=3
M.wl_shell_surface.interface[0].events=wl_shell_surface_events
local wl_surface_requests=ffi.new("struct wl_message[12]",{
{"destroy",
"",
args_types_nil
},
{"attach",
"?oii",
args_types_wl_surface_attach
},
{"damage",
"iiii",
args_types_nil
},
{"frame",
"n",
args_types_wl_surface_frame
},
{"set_opaque_region",
"?o",
args_types_wl_surface_set_opaque_region
},
{"set_input_region",
"?o",
args_types_wl_surface_set_input_region
},
{"commit",
"",
args_types_nil
},
{"set_buffer_transform",
"2i",
args_types_nil
},
{"set_buffer_scale",
"3i",
args_types_nil
},
{"damage_buffer",
"4iiii",
args_types_nil
},
{"offset",
"5ii",
args_types_nil
},
{"get_release",
"7n",
args_types_wl_surface_get_release
},
})
local wl_surface_events=ffi.new("struct wl_message[4]",{
{"enter",
"o",
args_types_wl_surface_enter
},
{"leave",
"o",
args_types_wl_surface_leave
},
{"preferred_buffer_scale",
"6i",
args_types_nil
},
{"preferred_buffer_transform",
"6u",
args_types_nil
},
})
M.wl_surface.interface[0].name=wl_surface
M.wl_surface.interface[0].version=7
M.wl_surface.interface[0].method_count=12
M.wl_surface.interface[0].methods=wl_surface_requests
M.wl_surface.interface[0].event_count=4
M.wl_surface.interface[0].events=wl_surface_events
local wl_seat_requests=ffi.new("struct wl_message[4]",{
{"get_pointer",
"n",
args_types_wl_seat_get_pointer
},
{"get_keyboard",
"n",
args_types_wl_seat_get_keyboard
},
{"get_touch",
"n",
args_types_wl_seat_get_touch
},
{"release",
"5",
args_types_nil
},
})
local wl_seat_events=ffi.new("struct wl_message[2]",{
{"capabilities",
"u",
args_types_nil
},
{"name",
"2s",
args_types_nil
},
})
M.wl_seat.interface[0].name=wl_seat
M.wl_seat.interface[0].version=10
M.wl_seat.interface[0].method_count=4
M.wl_seat.interface[0].methods=wl_seat_requests
M.wl_seat.interface[0].event_count=2
M.wl_seat.interface[0].events=wl_seat_events
local wl_pointer_requests=ffi.new("struct wl_message[2]",{
{"set_cursor",
"u?oii",
args_types_wl_pointer_set_cursor
},
{"release",
"3",
args_types_nil
},
})
local wl_pointer_events=ffi.new("struct wl_message[11]",{
{"enter",
"uoff",
args_types_wl_pointer_enter
},
{"leave",
"uo",
args_types_wl_pointer_leave
},
{"motion",
"uff",
args_types_nil
},
{"button",
"uuuu",
args_types_nil
},
{"axis",
"uuf",
args_types_nil
},
{"frame",
"5",
args_types_nil
},
{"axis_source",
"5u",
args_types_nil
},
{"axis_stop",
"5uu",
args_types_nil
},
{"axis_discrete",
"5ui",
args_types_nil
},
{"axis_value120",
"8ui",
args_types_nil
},
{"axis_relative_direction",
"9uu",
args_types_nil
},
})
M.wl_pointer.interface[0].name=wl_pointer
M.wl_pointer.interface[0].version=10
M.wl_pointer.interface[0].method_count=2
M.wl_pointer.interface[0].methods=wl_pointer_requests
M.wl_pointer.interface[0].event_count=11
M.wl_pointer.interface[0].events=wl_pointer_events
local wl_keyboard_requests=ffi.new("struct wl_message[1]",{
{"release",
"3",
args_types_nil
},
})
local wl_keyboard_events=ffi.new("struct wl_message[6]",{
{"keymap",
"uhu",
args_types_nil
},
{"enter",
"uoa",
args_types_wl_keyboard_enter
},
{"leave",
"uo",
args_types_wl_keyboard_leave
},
{"key",
"uuuu",
args_types_nil
},
{"modifiers",
"uuuuu",
args_types_nil
},
{"repeat_info",
"4ii",
args_types_nil
},
})
M.wl_keyboard.interface[0].name=wl_keyboard
M.wl_keyboard.interface[0].version=10
M.wl_keyboard.interface[0].method_count=1
M.wl_keyboard.interface[0].methods=wl_keyboard_requests
M.wl_keyboard.interface[0].event_count=6
M.wl_keyboard.interface[0].events=wl_keyboard_events
local wl_touch_requests=ffi.new("struct wl_message[1]",{
{"release",
"3",
args_types_nil
},
})
local wl_touch_events=ffi.new("struct wl_message[7]",{
{"down",
"uuoiff",
args_types_wl_touch_down
},
{"up",
"uui",
args_types_nil
},
{"motion",
"uiff",
args_types_nil
},
{"frame",
"",
args_types_nil
},
{"cancel",
"",
args_types_nil
},
{"shape",
"6iff",
args_types_nil
},
{"orientation",
"6if",
args_types_nil
},
})
M.wl_touch.interface[0].name=wl_touch
M.wl_touch.interface[0].version=10
M.wl_touch.interface[0].method_count=1
M.wl_touch.interface[0].methods=wl_touch_requests
M.wl_touch.interface[0].event_count=7
M.wl_touch.interface[0].events=wl_touch_events
local wl_output_requests=ffi.new("struct wl_message[1]",{
{"release",
"3",
args_types_nil
},
})
local wl_output_events=ffi.new("struct wl_message[6]",{
{"geometry",
"iiiiissi",
args_types_nil
},
{"mode",
"uiii",
args_types_nil
},
{"done",
"2",
args_types_nil
},
{"scale",
"2i",
args_types_nil
},
{"name",
"4s",
args_types_nil
},
{"description",
"4s",
args_types_nil
},
})
M.wl_output.interface[0].name=wl_output
M.wl_output.interface[0].version=4
M.wl_output.interface[0].method_count=1
M.wl_output.interface[0].methods=wl_output_requests
M.wl_output.interface[0].event_count=6
M.wl_output.interface[0].events=wl_output_events
local wl_region_requests=ffi.new("struct wl_message[3]",{
{"destroy",
"",
args_types_nil
},
{"add",
"iiii",
args_types_nil
},
{"subtract",
"iiii",
args_types_nil
},
})
M.wl_region.interface[0].name=wl_region
M.wl_region.interface[0].version=7
M.wl_region.interface[0].method_count=3
M.wl_region.interface[0].methods=wl_region_requests
M.wl_region.interface[0].event_count=0
M.wl_region.interface[0].events=wl_region_events
local wl_subcompositor_requests=ffi.new("struct wl_message[2]",{
{"destroy",
"",
args_types_nil
},
{"get_subsurface",
"noo",
args_types_wl_subcompositor_get_subsurface
},
})
M.wl_subcompositor.interface[0].name=wl_subcompositor
M.wl_subcompositor.interface[0].version=1
M.wl_subcompositor.interface[0].method_count=2
M.wl_subcompositor.interface[0].methods=wl_subcompositor_requests
M.wl_subcompositor.interface[0].event_count=0
M.wl_subcompositor.interface[0].events=wl_subcompositor_events
local wl_subsurface_requests=ffi.new("struct wl_message[6]",{
{"destroy",
"",
args_types_nil
},
{"set_position",
"ii",
args_types_nil
},
{"place_above",
"o",
args_types_wl_subsurface_place_above
},
{"place_below",
"o",
args_types_wl_subsurface_place_below
},
{"set_sync",
"",
args_types_nil
},
{"set_desync",
"",
args_types_nil
},
})
M.wl_subsurface.interface[0].name=wl_subsurface
M.wl_subsurface.interface[0].version=1
M.wl_subsurface.interface[0].method_count=6
M.wl_subsurface.interface[0].methods=wl_subsurface_requests
M.wl_subsurface.interface[0].event_count=0
M.wl_subsurface.interface[0].events=wl_subsurface_events
local wl_fixes_requests=ffi.new("struct wl_message[3]",{
{"destroy",
"",
args_types_nil
},
{"destroy_registry",
"o",
args_types_wl_fixes_destroy_registry
},
{"ack_global_remove",
"2ou",
args_types_wl_fixes_ack_global_remove
},
})
M.wl_fixes.interface[0].name=wl_fixes
M.wl_fixes.interface[0].version=2
M.wl_fixes.interface[0].method_count=3
M.wl_fixes.interface[0].methods=wl_fixes_requests
M.wl_fixes.interface[0].event_count=0
M.wl_fixes.interface[0].events=wl_fixes_events
return M
