--[[
DO NOT EDIT
This file is autogenerated from gen_lib.lua
To regenerate this file, run `nvim -l gen/lib.lua`
--]]

local ffi=require"ffi"
ffi.cdef[=[
struct wl_message { const char *name; const char *signature; const struct wl_interface **types; };
struct wl_interface { const char *name; int version; int method_count; const struct wl_message *methods; int event_count; const struct wl_message *events; };
typedef long unsigned int size_t;;
struct wl_array { size_t size; size_t alloc; void *data; };
typedef signed int __int32_t;;
typedef __int32_t int32_t;;
typedef int32_t wl_fixed_t;;
struct wl_proxy;
void wl_proxy_set_user_data(struct wl_proxy *proxy, void *user_data);;
void * wl_proxy_get_user_data(struct wl_proxy *proxy);;
typedef unsigned int __uint32_t;;
typedef __uint32_t uint32_t;;
uint32_t wl_proxy_get_version(struct wl_proxy *proxy);;
void wl_proxy_destroy(struct wl_proxy *proxy);;
struct wl_proxy * wl_proxy_marshal_flags(struct wl_proxy *proxy, uint32_t opcode, const struct wl_interface *interface, uint32_t version, uint32_t flags, ...);;
enum {WL_MARSHAL_FLAG_DESTROY=1};
]=]
return ffi.load"wayland-client" --[[@as table]]
